services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    hostname: redis
    image: "redis:latest"
    ports:
      - "6379:6379"